apiVersion: v1
kind: Secret
metadata:
  name: llm-stack-secret
  namespace: llm-stack
type: Opaque
data:
  # Postgres Secret -BASE64
  postgres-password: "POSTGRESPASSWORD"
  
  # LiteLLM Secrets - BASE64
  # url: postgresql://litellm:<POSGRESPASSWORD>@postgres.llm-stack.svc.cluster.local:5432/litellm_logs
  litellm-database-url: "postgresql://litellm:<POSGRESPASSWORD>@postgres.llm-stack.svc.cluster.local:5432/litellm_logs"
  # key: sk-sahaskdhasdaskj -BASE64
  litellm-master-key: "LITELLMMASTERKEY"
  
  # Cloudflare Tunnel Secret -BASE64
  cloudflared-token: "CLOUDFLARETOKEN"
